### ISSUE TITLE
Implement serder

### ISSUE THREAD

**Issue by m00sey** [WebOfTrust/cesride#10]
Serder is versioned protocol key event message serializer-deserializer class.

Requires #14.

impl - https://github.com/WebOfTrust/keripy/blob/5a19417a3c6e79e868ae96f55e82385de0c348d3/src/keri/core/coring.py#L4852

test - https://github.com/WebOfTrust/keripy/blob/5a19417a3c6e79e868ae96f55e82385de0c348d3/tests/core/test_coring.py#L5040

**Comment by jasoncolburne** [comment]
wip on this

**Comment by jasoncolburne** [comment]
serder requires tholder which is not really a cesride concept. nonetheless I will implement tholder in this work and we can extract it later.

**Comment by jasoncolburne** [comment]
I believe this may be all that is required to start making examples, so i may throw one in here as well
