### ISSUE TITLE
Implement seqner

### ISSUE THREAD

**Issue by m00sey** [WebOfTrust/cesride#11]
Seqner is subclass of Matter, cryptographic material, for ordinal numbers such as sequence numbers or first seen ordering numbers.
    
Seqner provides fully qualified format for ordinals (sequence numbers etc) when provided as attached cryptographic material elements.

Useful when parsing attached receipt groupings with sn from stream or database.

Requires #8 
    
impl - https://github.com/WebOfTrust/keripy/blob/5a19417a3c6e79e868ae96f55e82385de0c348d3/src/keri/core/coring.py#L1249

test - https://github.com/WebOfTrust/keripy/blob/5a19417a3c6e79e868ae96f55e82385de0c348d3/tests/core/test_coring.py#L2586

**Comment by DmitryKuzmenko** [comment]
WIP on this.
