### ISSUE TITLE
Implement saider

### ISSUE THREAD

**Issue by m00sey** [WebOfTrust/cesride#13]
Saider is Matter subclass for self-addressing identifier prefix using derivation as determined by code from key event dictionary (ked, a python implementation detail).

Requires #8.

impl - https://github.com/WebOfTrust/keripy/blob/5a19417a3c6e79e868ae96f55e82385de0c348d3/src/keri/core/coring.py#L3162

test - https://github.com/WebOfTrust/keripy/blob/5a19417a3c6e79e868ae96f55e82385de0c348d3/tests/core/test_coring.py#L4600

**Comment by jasoncolburne** [comment]
Looks like saider depends on the `sad` data structure, and `Sadder` depends on `Saider`. It appears it is easiest to start with Saider, even though that is counter-intuitive to me.

**Comment by jasoncolburne** [comment]
not actively working on this, someone else can take it

**Comment by jasoncolburne** [comment]
working on this again. no dependency on `Sadder`, but we do need a dict-y data type
