### ISSUE TITLE
Implement sadder

### ISSUE THREAD

**Issue by m00sey** [WebOfTrust/cesride#14]
Sadder is self addressed data (SAD) serializer-deserializer class.

impl - https://github.com/WebOfTrust/keripy/blob/5a19417a3c6e79e868ae96f55e82385de0c348d3/src/keri/core/coring.py#L4603

**Comment by jasoncolburne** [comment]
not actively working on this, someone feel free to take it

**Comment by jasoncolburne** [comment]
working on this again
