### ISSUE TITLE
Re-configure Codecov

### ISSUE THREAD

**Issue by jasoncolburne** [WebOfTrust/cesride#39]
Codecov started running checks in a recent PR, we're unsure why. Investigate and determine the appropriate settings moving forward.

In particular, the `diff` action/job seems to be failing, leading to a failed CI run.

**Comment by m00sey** [comment]
I had a notification to "approve" updated codecov settings. I'm wondering if that makes any difference moving forward.

**Comment by jasoncolburne** [comment]
I fixed this in the pending `Counter` PR.

**Comment by jasoncolburne** [comment]
I have thought about this. After increasing coverage to 98%, it's going to be hard to ensure PRs match previous coverage. We are likely better off setting a threshold in `codecov.yml` of 95-97%.
