### ISSUE TITLE
Allow dead code warnings

### ISSUE THREAD

**Issue by jasoncolburne** [WebOfTrust/cesride#60]
We have this in our lib file(s):

```
// TODO: remove before 1.0.0
#![allow(dead_code)]
```

We need to remove it and clean up dead code before releasing 1.0.0.

**Comment by kentbull** [comment]
I will take this on.

**Comment by daidoji** [comment]
Gave a shot at this one for the hell of it in https://github.com/WebOfTrust/cesride/pull/153

**Comment by m00sey** [comment]
Closed by #153
