### ISSUE TITLE
Implement Prefixer

### ISSUE THREAD

**Issue by m00sey** [WebOfTrust/cesride#68]
Prefixer is Matter subclass for autonomic identifier prefix using derivation as determined by code from key event dictionary

Requires https://github.com/WebOfTrust/cesride/issues/8.

impl - https://github.com/WebOfTrust/keripy/blob/5a19417a3c6e79e868ae96f55e82385de0c348d3/src/keri/core/coring.py#L2878

test - https://github.com/WebOfTrust/keripy/blob/8a6f67153594ffac0dd3a2ccfbc4fd9235194d79/tests/core/test_coring.py#L4282

**Comment by jasoncolburne** [comment]
Working on this.
