### ISSUE TITLE
Implement siger

### ISSUE THREAD

**Issue by m00sey** [WebOfTrust/cesride#7]
Siger is subclass of Indexer, indexed signature material.

Requires #1 

impl - https://github.com/WebOfTrust/keripy/blob/5a19417a3c6e79e868ae96f55e82385de0c348d3/src/keri/core/coring.py#L2113

test - https://github.com/WebOfTrust/keripy/blob/5a19417a3c6e79e868ae96f55e82385de0c348d3/tests/core/test_coring.py#L4543

[siger.ts](https://github.com/WebOfTrust/signify-ts/blob/main/src/keri/core/signer.ts)

**Comment by m00sey** [comment]
requires #1

**Comment by jasoncolburne** [comment]
Working on this.

**Comment by jasoncolburne** [comment]
This issue is cross listed - it references signer code but was labelled siger. I'll make another issue for `Signer`.
