### ISSUE TITLE
Consider using `rstest`

### ISSUE THREAD

**Issue by jasoncolburne** [WebOfTrust/cesride#70]
We have the option to clean up our test code by using a crate called `rstest`. This will allow us to do things like select sets of parameters and expected results to test over, executing common code many times, rather than having long sequences of the same code or multiple test functions doing essentially the same thing.

https://docs.rs/rstest/latest/rstest/#creating-parametrized-tests
https://docs.rs/rstest/latest/rstest/#creating-a-test-for-each-combinations-of-given-values
https://docs.rs/rstest/latest/rstest/#magic-conversion

**Comment by jasoncolburne** [comment]
I am in favour of this, and I'm willing to do the work (tonight even) to bring the rest of the library in sync with #69 if we merge it.

**Comment by m00sey** [comment]
I like the approach.

**Comment by jasoncolburne** [comment]
https://github.com/WebOfTrust/cesride/pull/71
