### ISSUE TITLE
Clean up `Counter`

### ISSUE THREAD

**Issue by jasoncolburne** [WebOfTrust/cesride#94]
Counter is an abstract class in `KERIpy` and should likely be a trait. First determine how it is used, as I didn't see it used in abstract in `coring.py`. If it makes sense, follow the patterns in the other traits.

**Comment by kentbull** [comment]
### Meeting comment 3-30-23

There's not a problem, this ticket is not worth doing, since anything doesn't derive from Counter right now. We will close this. If there is work we need to do later then we will make a new issue.
